### ISSUE TITLE
ข้อ Terz Traversal Example ข้อแรกผิดรึป่าวครับ

### ISSUE THREAD

**Issue by Palmkonde** [Anon-136/otog-frontend#11]
ผมทำ Testcase แรก ได้ F ครับ
แล้วก็ลองส่งดูก็ผ่านหมดครับ

**Comment by Nepumi-Jr** [comment]
แก้ให้แล้วครับ
ก็ตามนั้นแหละครับ Input ควรเป็น `10 10 6...` ไม่ควรเป็น `10 10 5` เนอะ

แล้วก็ถ้ามีปัญหาโจทย์อะไรก็ แนะนำให้พิมพ์ในแชท OTOG (หรือจะใช้ Bot Otog ในดิสคอร์ดก็ได้) นะครับ
พวกพี่ ๆ ขยันอ่านกันอยู่ครับ เพราะแชทเหงามาก ๆ 5555555
พอดี Repo นี้มันเป็น Repo ที่ว่าด้วยเรื่องของการออกแบบและโค้ด Front end นะครับ
มันควรที่จะ Open Issue ที่เป็นลักษณะโจทย์นะครับ

ด้วยรักและห่วงใยจาก**โอวัลติน**
